version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    environment:
      RAILS_ENV: development
      EDITOR: vim
      MECAB_PATH: /usr/lib/x86_64-linux-gnu/libmecab.so.2
    volumes:
      - .:/app
      - bundle_install:/usr/local/bundle
    links:
      - db
    ports:
      - "3000:3000"
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    volumes:
      - minio:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
volumes:
  mysql-data:
    driver: local
  bundle_install:
    driver: local
  minio:
    driver: local
