default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: pass
  host: db

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  host: <%= Rails.application.credentials.db_host %>
  database: production
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_pass %>
